version: '3.1'

services:
    postgres:
        container_name: postgresql
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: passmanager
            PGDATA: /data/postgres
        volumes:
          - ./pg:/data/postgres
        ports:
          - 5432:5432
    adminer:
      container_name: adminer
      image: adminer
      restart: always
      ports:
        - 8088:8080
      depends_on:
        - postgres
    php:
        container_name: php-fpm
        build: 
          context: ./php
        ports:
          - 9000:9000
        depends_on:
          - postgres
        volumes:
          - ./app:/var/www/
    nginx:
      container_name: nginx
      build:
        context: ./nginx
      ports:
        - 8888:80
      volumes:
        - ./app:/var/www/
        - ./app/storage/app/public:/var/www/public/storage
        - ./nginx/logs:/var/log/nginx
      depends_on:
        - php
        - postgres